### ISSUE TITLE
Error of RealOpInsight Worstation startup in windows

### ISSUE THREAD

**Issue by bzhpwr** [RealOpInsightLabs/realopinsight-workstation#51]
Hi,

When I start RealOpInsight Worstation 3.1.0 on windows 7 Pro 64 bits, I have an non critical error (ROI worstation still working) at startup: 

![roi error 1](https://cloud.githubusercontent.com/assets/8058013/4524292/66d95b58-4d42-11e4-8a82-01f4469c91af.png)

Thank,

**Comment by jameseriot** [comment]
Can't be reproduced
