### ISSUE TITLE
link ROI maps

### ISSUE THREAD

**Issue by bzhpwr** [RealOpInsightLabs/realopinsight-workstation#52]
Hi again,

I try to a make a too big maps and it's not usefull in roi because the maps is too large for my screen.

So I want to ask you if you think it's possible to have a maps as a service. I'll explain me.

Can I take a result of a root business service (top of map) and set it as a service in a new map. So if the root business service is critical, the map(s) linked with it is "critical".
Ex: I have made a map of my citrix XenApp server. So if my server are not ok, the next maps (application on citrix XenApp server ) linked with it is not ok 

I'm sorry if I'm not clear :)

Thank, Bye.

**Comment by rchakode** [comment]
Hi, 
This enhancement will be implemented in the next release of RealOpInsight.

**Comment by rchakode** [comment]
Fixed in https://github.com/RealOpInsightLabs/realopinsight-workstation/commit/9907909d2fb5387a67f47c5511c0b87cb94ccc85
