### ISSUE TITLE
No Qosdata for new map.

### ISSUE THREAD

**Issue by bzhpwr** [RealOpInsightLabs/realopinsight-workstation#60]
Hi @RealOpInsightLabs 

Happy new year 2015 ! 

I'm back with bug ( or mistake I don't know :) ) !

I import a new map in RealOpInsight Ultimate, it's working but there is no graph on Ops Home for this map.

So I looked in qosdata table, and there is no data for my view name.

Nothing in log files too.

Thanks

**Comment by rchakode** [comment]
Hi @bzhpwr,
Thanks and happy new year to you too.

About your problem:
1) Check that the RealOpInsight QoS Collector is running
2) If not, restart it. 
3) Select specific report dates and set the end date to tomorrow and apply
4) If still not graph, restart the QoS collector 

Let's know if the problem persists.

Rergards,

**Comment by bzhpwr** [comment]
I restart realopinsight-reportd and now in the logs I have QOS entry for my map.

I have graph too. It's all right. 

Thanks.

**Comment by rchakode** [comment]
This sounds good, I'll close the ticket.
