### ISSUE TITLE
Cannot run any Workstation version

### ISSUE THREAD

**Issue by zaitsxl** [RealOpInsightLabs/realopinsight-workstation#63]
Hi,

for a few days I've been trying to start Workstation under Windows. I've tried on Windows 7 x64 and Windows 8.1 x64. In both cases when I start operations console and choose description file QT throws the following exception:

Assertion failed!
File: ..\ngrt4n-qt\core\src\DashboardBase.cpp, Line 569
Expression: root != m_cdata->bpnodes.end()

Tried to run as administrator. Tried versions 3.2.1, 3.1.1, 3.1.0, 3.0.5. No success. Anybody has an idea what to do?

Thanx,
Alexander

**Comment by rchakode** [comment]
Hi Alexender,
Your description file seems to be  not well built.
To be sure, try with our built-in description files located under the examples direcrory from source tree.
if the problem persists, let's know. Otherwise, recreate your description file using RealOpInsight Editor.
regards,

**Comment by zaitsxl** [comment]
Hi,

well that description file was built by Editor that was installed from the bundle package. I just opened  Editor and pressed "Import Zabbix triggers". Import was successful so I've saved description file. And then I couldn't use it in Operations Console with the above error. That's the story. However you're right, your sample description files are working. What should I do then?

Regards,
Alexander

**Comment by rchakode** [comment]
This means probably a problem with the Zabbix IT service importation feature.
If possible, can you send us the resulting description file ? by email (if confidential) or attached there.
If needed you could modify the names of your services.

Otherwise, to create a description file from scrach, just open the editor and create your own hierarchy. For that, you may need to take a look at the Editor user guide : http://docs.realopinsight.com/latest/01_workstation/editor-manual.html

**Comment by zaitsxl** [comment]
Hi,

well manual file creation is an interesting game, I'm sure :-) But can I use automatic one? It doesn't show any errors on import, so probably it supposed to work.... Anyway what's the email I can send file to?

Regards,
Alexander

**Comment by rchakode** [comment]
Sure, we also think that importation would be better. But in your it smells like there is problem.
Our email: contact@realopinsight.com

**Comment by rchakode** [comment]
Hi again Alexender,
To learn more about your that seems weird regarding the importation feature, did you modify the view after The importation?

**Comment by zaitsxl** [comment]
Hi Rodrigue,

well actually no, I've just imported Zabbix triggers and saved the
description file. How I supposed to do that?
And here's even more important thing. Operations Console runs nicely with
bundled example description files. My final goal is to get board looking
like in your demo, or like on screenshots. I mean these 3 big red, yellow
and green tiles showing total status of monitored systems. How can I get
that? I couldn't find that in tutorials. BTW I already installed Ultimate
version and cannot see such options there too

Regards,
Alexander

2015-02-10 20:32 GMT+02:00 Rodrigue Chakode <notifications@github.com>:

> Hi again Alexender,
> To learn more about your that seems weird regarding the importation
> feature, did you modify the view after The importation?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/63#issuecomment-73755093>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by jameseriot** [comment]
Hi Alexander,

If you want, we could help you debug your imported description file. Please mail us the resulting file, this would also help us find what happens during the importation and, if applicable, provide a patch for the future.

Otherwise, the principle of running RealOpInsight Ultimate is very straightforward, Just take a look at the documentation: http://docs.realopinsight.com/latest/02_ultimate/index.html.

But in short, you can proceed as follows:

1. create your description files
2. log into RealOpInsight Ultimate as administrator
3. import your description files (See Import menu)
4. create users and assign the imported description files to them. Must sure that the users have the Operator role,  not administrator
5. log into RealOpInsight Ultimate as  regular user (previously created), you should see the view assigned to you. Like in the demo.
6. that's all. Just enjoy the rest. 

Regards,
James,

**Comment by zaitsxl** [comment]
Hi James,

ahaa, so that "3 tiled" view is specific for non-administrators. I could get it by your description, thanx. Let me now dig into my own description file and maybe it will finally work

Regards,
Alexander

**Comment by jameseriot** [comment]
ya !
You could assign any number of views to your different users. You can even assign the same view to many user. The limit is your mind... 

Good luck, and in any case, send us your feedback ;)

**Comment by zaitsxl** [comment]
Hi James,

what I got from manual for now is that I have to create some kind of hierarchy and assign Zabbix data point per each item. Having 3500 triggers makes this task a bit boring. Can I just import all the triggers into single hierarchy item? I need this board only to see if something needs attention and if so I can see details in Zabbix. So can I or going manual is the only way?

Regards,
Alexander

**Comment by jameseriot** [comment]
:)
When you think business service monitoring (BSM), what RealOpInsight aims to address, importing 3500 triggers just like a bundle does not make sense IMHO.
Dealing with BSM, you have target services (e.g. a application, a platform...), and metrics (what we call data point) that correlate together make sense regarding the overall status of your target.

Otherwise, to ease the setup of  data point, the RealOpInsight allows you to automatically import your Zabbix triggers and  deal with assignation in few clicks : http://docs.realopinsight.com/latest/01_workstation/editor-manual.html#importing-zabbix-triggers

**Comment by zaitsxl** [comment]
Hi,

yes that definitely could be that it's not right kind of software for such purposes. But I couldn't find any other solution that provides getting data from Zabbix and showing it in a form of brief summary (like your 3 tiles). However it looks like importing Zabbix triggers doesn't go well. I see all my triggers in Editor, but after saving description file it appears empty. I see that only one Zabbix trigger was picked up, the one that I highlighted in Editor. In your sample configs I see that multiple triggers can be assigned to a single hierarchy item. What am I doing wrong? (see attached file, remove JPG at the end
![id zbx ngrt4n xml](https://cloud.githubusercontent.com/assets/10940392/6146461/9167a3c6-b1f5-11e4-8779-888cd0fbd634.jpg)
)

Regards,
Alexander

**Comment by jameseriot** [comment]
(Your image is not accessible)
No, a trigger can be assigned to only single data point (leave node in the hierarchy): http://docs.realopinsight.com/latest/00_intro/concepts.html#dashboard-as-a-hierarchy-of-services

But many data point can be linked to a same trigger. 

So, the importation only avoids you to type each trigger name manually, this does not replace the process of linking each child node of your hierarchy to a trigger? 

BTW, aggregation does not mean a bundle of everything, and that's not the aim of RealOpInsight, sorry if that's what you're looking for.

**Comment by zaitsxl** [comment]
HI,

yes that's my bad terminology. I meant multiple triggers liked to a single data point. My attached file is not an image, it's XML description file, I've just added JPG extension to fit into this chat. You can download it and rename back to see the contents.

So you claim that those 3 tiles does not really show summary of how many triggers are in "OK", "warning" and "failure" states? (green, yellow and red correspondingly)

Regards,
Alexander

**Comment by jameseriot** [comment]
What you see in the demo is not related to the status of triggers directly, but the status of the related business views.
In the demo, we have three business views. The fact that it's green, red, yellow..., just shows the overall status of the three business views after correlating the underlying triggers' status.

**Comment by jameseriot** [comment]
Otherwise, we could mark this as a feature. Probably for a specific product.

**Comment by zaitsxl** [comment]
Hi,

ok guys, one last question for you. If I create single business service, then one IT service under it, then import all my Zabbix triggers into this IT service. Will it show me the status of this business service in form of these 3 colored tiles? I mean green if all triggers are ok, yellow of some are faulty, and red of lot are faulty

Regards,
Alexander

**Comment by jameseriot** [comment]
Yes, sure. What is basically a business service that relies on all your triggers :)

**Comment by zaitsxl** [comment]
Hi,

OK, that.s great to hear. So problem is probably in too many data points for a single service. Can you suggest what can we do here?

Regards,
Alexander

**Comment by rchakode** [comment]
Do you mean how to do this quickly ?
If yes, we could help in providing specific tool/script to do that. In this case, we may ask you a counterparty that we can talk about by private email, of course if your are interested.

**Comment by zaitsxl** [comment]
Hi,

well yes, if you say it can display summarized status like I asked above. Besides I believe this isn't an expected behavior since there are no trigger limits mentioned in your documentation. Some other customers may also face this. I'm ready for cooperation

Regards,
Alexander

**Comment by jameseriot** [comment]
There is not limit about the number of triggers.
What we propose is just a script to import all your Zabbix trigger to build a bundle business view description file.
Again, there is not limitation concerning the number of triggers RealOpInsight can handle.

**Comment by zaitsxl** [comment]
Hi,

if we could compose such script it would be great

Regards,
Alexander

**Comment by jameseriot** [comment]
Well, 
can you drop us an email? It would be better to continue the discussion by email: support@realopinsight.com or contact@realopinsight.com

**Comment by jameseriot** [comment]
fixed in  3.2.2
