### ISSUE TITLE
cannot import from zabbix 2.4.4

### ISSUE THREAD

**Issue by andreaconsadori** [RealOpInsightLabs/realopinsight-workstation#65]
hi, i've the same issue on zabbix 2.4.4, i cannot import trigger.

if i try the command i can see in the thread

with -h
HTTP/1.1 200 OK
Date: Tue, 10 Mar 2015 09:43:19 GMT
Server: Apache/2.2.15 (CentOS)
X-Powered-By: PHP/5.4.37
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: POST
Access-Control-Max-Age: 1000
Content-Length: 124
Connection: close
Content-Type: application/json

without -h
HTTP/1.0 412 Precondition Failed
Date: Tue, 10 Mar 2015 09:43:46 GMT
Server: Apache/2.2.15 (CentOS)
X-Powered-By: PHP/5.4.37
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: POST
Access-Control-Max-Age: 1000
Content-Length: 0
Connection: close
Content-Type: text/html; charset=UTF-8

![zabbix-realops](https://cloud.githubusercontent.com/assets/1265395/6572471/c6475280-c712-11e4-8387-9ccff1b08e7b.JPG)

**Comment by jameseriot** [comment]
Hi @andreaconsadori 
I suppose you have this issue after within the RealOpInsight Editor.

So similarly to what was discussed in the aforementioned thread, check that you selected an appropriate source type in the RealOpInsight Configuration Manager. The source type must be Zabbix. 

Looking forward to hearing from you.

**Comment by andreaconsadori** [comment]
![zabbix](https://cloud.githubusercontent.com/assets/1265395/6573335/07fb0b48-c71a-11e4-8fb6-016ea4e8b0ec.JPG)

as you can see the source is ok

**Comment by jameseriot** [comment]
yes, seems OK!

Have you experienced this with other versions of Zabbix ?

BTW, we'll try to reproduce that with Zabbix 2.4.4. 
RealOpInsight has been tested with Zabbix 2.4.0, so we need to investigate to know if the problem comes from Zabbix 2.4.4 or just a corner bug in RealOpinsight. 

regards

**Comment by jameseriot** [comment]
Hi @andreaconsadori 
We are not able to reproduce this bug, and would like to get more information in the situation that raised that. 
So could you tell us if you used a filter when importing your Zabbix triggers? If yes, did you used special characters in your filter ?

Looking forward to hearing from you.
Regards,

**Comment by andreaconsadori** [comment]
i use no filtermaybe a wireshark dump while importing could help?



 


Date: Tue, 17 Mar 2015 08:42:32 -0700

**Comment by jameseriot** [comment]
yes, a wireshark dump could be helpful indeed.

Before doing so, could you try to make an importation while using "Zabbix servers"  as filter -- but without quotes ?

**Comment by andreaconsadori** [comment]
with this filter it works.... so maybe i've to import per group and not globally?


 


Date: Tue, 17 Mar 2015 09:13:10 -0700

**Comment by jameseriot** [comment]
Good to hear that.
Indeed, as recommended in the documentation [1], importing monitoring items group by group has many advantages.

But, I think there is another problem there and I suspect some special characters in trigger names are not well handle by RealOpInsight.

[1] http://docs.realopinsight.com/latest/04_tutorials/import-checks-as-host_group-business-view.html

**Comment by jameseriot** [comment]
Can't be reproduced, suggestion is to use the above workaround
