### ISSUE TITLE
data points with commas in their name

### ISSUE THREAD

**Issue by thermic** [RealOpInsightLabs/realopinsight-workstation#66]
Greetings!

Using roi workstation 3.2.2, having it connected to a Zabbix 2.2 server. Can successfully retrieve my triggers. Some of the triggers have commas in their name, i.e.:
PSU broken (PSU 1: {ITEM.LASTVALUE1}, PSU 2: {ITEM.LASTVALUE2})

When I try to use this trigger as a data point, I noticed the data point is stored properly in the XML, i.e. <SubServices>Source0:xxxx/PSU broken (PSU 1: {ITEM.LASTVALUE1}, PSU 2: {ITEM.LASTVALUE2})</SubServices>

However when I re-select my IT Service, only a fraction of the Data Point is shown, up to the comma, i.e.
PSU broken (PSU 1: {ITEM.LASTVALUE1}

When I open the XML in ROI ultimate, it shows for this data point:
Undefined service (Source0:xxxx/PSU broken (PSU 1: {ITEM.LASTVALUE1})

I think this needs to be fixed in both workstation and ultimate.

**Comment by jameseriot** [comment]
Hi @thermic 

Thanks for this report.
you actually identified the cause. Indeed, RealOpInsight uses commas as separator for data points in the XML file, hence it thinks that the commas in triggers names are separators too. We're working to fix that quickly. 

Regards,

 James

**Comment by jameseriot** [comment]
Hi @thermic 

Could you send me the fragment of the XML file where you have *Source0:xxxx/PSU broken (PSU 1: {ITEM.LASTVALUE1}, PSU 2: {ITEM.LASTVALUE2})* ?

Just the node definition is sufficient.

**Comment by thermic** [comment]
@jameseriot yes of course:

    <Service id="ngrt4nsrv0a58eb6cf278441b8a80eb8ec518b8a726"  type="1"  statusCalcRule="0"  statusPropRule="0"  weight="1">
     <Name>psu</Name>
     <Icon>Hypervisor</Icon>
     <Description></Description>
     <AlarmMsg></AlarmMsg>
     <NotificationMsg></NotificationMsg>
     <SubServices>Source0:s0912/PSU broken (PSU 1: {ITEM.LASTVALUE1}, PSU 2: {ITEM.LASTVALUE2})</SubServices>
    </Service>

**Comment by jameseriot** [comment]
Hi @thermic 
Can't reproduce this with a false description file that contain your definition.
Perhaps this is related to issue #67 you also reported ? I.e. may be the wrong trigger is considered ?

**Comment by jameseriot** [comment]
No feedback. Can't be reproduced
