### ISSUE TITLE
Error in website

### ISSUE THREAD

**Issue by andreaconsadori** [RealOpInsightLabs/realopinsight-workstation#68]
i was looking for docs that describe how to import realopinsight workstation view in utilmate and on web page

http://realopinsight.com/products/realopinsight-ultimate

i click on QuickStart Guide and under Next Step i click  RealOpInsight Ultimate documentation

http://docs.realopinsight.com/3.0/02_ultimate/index.html

and it is a 404 page

**Comment by jameseriot** [comment]
Hi @andreaconsadori 

Thanks for the report. It's fixed now.
