### ISSUE TITLE
Weird response received from the server

### ISSUE THREAD

**Issue by skyfish69** [RealOpInsightLabs/realopinsight-workstation#69]
I deploy the zabbix_2014b8 OVA by downloading from the website. I happen the issue that couldn't get the data from the zabbix server , by the way the monitoring source configuration is correct and i verified it successfully on the realopinsight workstation . 
![image](https://cloud.githubusercontent.com/assets/9690087/7247793/e875b0e2-e83f-11e4-99c6-8c4ab12a3b86.png)

Version info:
zabbix:2.4
realopinsight ultimate :2014b8
realopinsight workstation:3.2.2(ibericus)

**Comment by jameseriot** [comment]
Hi @skyfish69 
Do you mean that everything works with RealOpInsight Workstation, but not with the Ultimate Edition?

**Comment by skyfish69** [comment]
yes, zabbix version 2.4.0 . Currently i couldn't get any useful log info in the path /opt/realopinsight/log/ Where can i check the log to see what happen ,API access or something else ?

**Comment by jameseriot** [comment]
This seems really weird indeed.
I suspect some problem with your description file, notably when I see service names with colon ':'.

It's possible that you send me your description file for further investigation? By private email if you want (support@realopinsight.com)

**Comment by jameseriot** [comment]
Now fixed in RealOpInsight Ultimate version 2015r2 just released
