### ISSUE TITLE
Binary download link wrong path

### ISSUE THREAD

**Issue by bzhpwr** [RealOpInsightLabs/realopinsight-workstation#74]
Hi @RealOpInsightLabs 

I'm following your tutorial http://docs.realopinsight.com/latest/02_ultimate/installation.html#id7 and I find a mistake:

- http://realopinsight.com/downloads
Binary Installation & Upgrade 	 Ubuntu Server 14.04 - 64 bits LTS 	2015r2 	08-06-2015

Point to a wrong file ->
http://sourceforge.net/projects/ngrt4n/files/RealOpInsight%20Ultimate/2015r2/realopinsight-ultimate-2015r2.thumbpatch.ubuntu.14.04.02.x86_64.ova.zip/download

I have downloaded a ova file but I want a binary.

Thank for your reply.

**Comment by bzhpwr** [comment]
I founded the good link. If someone need it:
http://sourceforge.net/projects/ngrt4n/files/RealOpInsight%20Ultimate/2015r2/realopinsight-ultimate-2015r2.thumbpatch.ubuntu1404.x86_64.tar.gz/download

**Comment by rchakode** [comment]
Hi @bzhpwr 
Thanks for the report, it's fixed now with the correct link (the same you found :+1: )

**Comment by bzhpwr** [comment]
Thanks
