### ISSUE TITLE
little change for realopinsight-restore 

### ISSUE THREAD

**Issue by bzhpwr** [RealOpInsightLabs/realopinsight-workstation#76]
Hi, 

I use realopinsight-backup and realopinsight-restore.

It's well working.

Just a few thing: Can you change script realopinsight-restore  for restart realopinsight-reportd because after restore, value aren't write in database because of realopinsight-reportd I think.

Thank you

**Comment by rchakode** [comment]
Thanks, marked for improvements

**Comment by jameseriot** [comment]
Hi @bzhpwr 

We are releasing the 1st release candidate of RealOpInsight Ultimate 2015r3 that would bring improvements regarding this issue: http://sourceforge.net/projects/ngrt4n/files/RealOpInsight%20Ultimate/2015r3/

You can test it and send feedback. Note that this release comes with a built-in http server to avoid some problem related to Apache + FastCGI. 

As usual the upgrade process shall be transparent, the old Apache config will be disabled.

**Comment by rchakode** [comment]
fixed 2015r3.b1
