### ISSUE TITLE
Autologon option request

### ISSUE THREAD

**Issue by zaitsxl** [RealOpInsightLabs/realopinsight-workstation#81]
Hi,

we're almost happy with your current version of RealOp Ultimate, however one crucial thing is missing. Is it possible to add autologon option? I mean something like checkbox "Remember me" on logon form. This will allow us to put board to autorun and have it opened once PC is turned on or rebooted

Regards,
Alexander

**Comment by RealOpInsightLabs** [comment]
Hi,
Thanks to recall this feature.
We added it in our back log.
We can't unfortunately provide a schedule for its implementation at this time. 
We have to satisfy some pending custom developments.

**Comment by zaitsxl** [comment]
Hi,

you can close this issue since we stopped using your product

Regards,
Alexander

**Comment by RealOpInsightLabs** [comment]
Hi,

Thank you for the information. We'll close it.
