### ISSUE TITLE
Console fails to load

### ISSUE THREAD

**Issue by zaitsxl** [RealOpInsightLabs/realopinsight-workstation#83]
Hi,

recently we faced the following issue: we create business service which consists of around 6000 Zabbix triggers and when we try to open it in RealOp Ultimate it keeps loading for a while and then returns to a logon screen. Yes we realize that 6000 triggers is quite a lot, however if that's just a matter of providing more hardware resources or changing some settings - fine by me. Please advise

Regards,
Alexander

**Comment by rchakode** [comment]
Hi Alexander,

This behavior is likely due to a lack of memory at some point during the load.

But I would suggest you to use interactive tools like top/atop/free to monitor your system during the load, so you will be able to see if the failure is due to a lack of resources  (cpu/memory).

**Comment by zaitsxl** [comment]
Hi,

so you believe that's only lack of hardware resources? All the settings of Apache and whatever else cannot affect this?

Regards,
Alexander

**Comment by rchakode** [comment]
Apache is no longer used by RealOpInsight, as of version 2015r3, which now comes with its built-in http server to overcome problems related to Apache in previous versions.

**Comment by zaitsxl** [comment]
Hi,

today I've checked what's happening with hardware resources during the above procedure. There is more than half of free memory (2.7 Gb). CPU load sometimes rises to 100% but that shouldn't lead to any fail, just slow operation. What else can we check?

Regards,
Alexander

**Comment by rchakode** [comment]
Ok, can you look at the log file and tell me if you find something weird ?

**Comment by zaitsxl** [comment]
Hi,

I looked at the log file and all I could see is "Console update triggered" message, then "Console update completed" and then "Session closed". Any more ideas what to check?

Regards,
Alexander

**Comment by rchakode** [comment]
Thanks for the feedback.

Can you time the loading process and tell me approximately the amount of time after which the session is closed. I need this to check some timeout parameters.

**Comment by zaitsxl** [comment]
Hi,

it's about 18 minutes according to log timestamps

Regards,
Alexander

**Comment by zaitsxl** [comment]
Hi,

so should we increase some timeouts elsewhere?

Regards,
Alexander

**Comment by rchakode** [comment]
Hi Alexander,

This value (18 min) is not coherent with any timeout in the settings. So can I ask you to time that without relying on the log timestamp ?

**Comment by zaitsxl** [comment]
Hi,

so you say that me with stopwatch will measure this timeframe more precisely than application internally did? Let's play with available timeouts instead, where can I find them?

Regards,
Alexander

**Comment by rchakode** [comment]
Ok.

You should find various timeout settings in the file /opt/realopinsight/etc/wt_config.xml

**Comment by zaitsxl** [comment]
Hi,

FYI I changed session timeout to 86400 seconds and server push timeout to 1440 seconds. Now board of 5000 triggers loads, pretty slow though but at least not logging off.

Regards,
Alexander

**Comment by rchakode** [comment]
Many thanks for your feedback.
I'm curious to have a screenshot of your 5000 triggers-based dashboard.

Can you share that with us ?

**Comment by zaitsxl** [comment]
Hi,

well that's only one business service and so only one tile. Not much to see


2015-12-21 17:59 GMT+02:00 Rodrigue Chakode <notifications@github.com>:

> Many thanks for your feedback.
> I'm curious to have a screenshot of your 5000 triggers-based dashboard.
>
> Can you share that with us ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RealOpInsightLabs/realopinsight-workstation/issues/83#issuecomment-166340570>
> .
>



-- 
In DOS we trust. Alexander Zaitsev

**Comment by rchakode** [comment]
Fixed
