### ISSUE TITLE
Contact email isn't working for realopinsightlabs

### ISSUE THREAD

**Issue by uow-dmurrell** [RealOpInsightLabs/realopinsight-workstation#84]
Can't email contact@realopinsight.com, is the project dead?

**Comment by rchakode** [comment]
Hi David,
Sorry for that. 
We're migrating our IT resources and have encountered disruptions in the email service.
We're working to fix everything, so RealOpInsight project is alive.

**Comment by rchakode** [comment]
We'll let you know when the issue will be fixed.

**Comment by rchakode** [comment]
Hi @uow-dmurrell 
Everything is now fixed. 
Again, many thanks for your feedback and sorry for the inconvenience.

Cheers,
